### PR TITLE
Remove allowEdit from the Summit_Events_Registrant

### LINKED ISSUE #205: guest user permission set assignment error - Winter '21 release
FIELD_INTEGRITY_EXCEPTION, The user license doesn't allow the permission: Edit Summit_Events_Appointments__c: []

Exception in task config_dev.deploy_guest_permission_set

Error: Apex error: System.DmlException: Upsert failed. First exception on row 0

Suggested fix: 
remove allowEdit permissions on Summit_Events_Appointments__c and Summit_Events_Registration__c objects from the permission set Terry_Summit_Events_Registrant

This means all guest user invoked update DML will need to execute in system context without sharing -- which may already be the case?

An alternative solution would be a massive refactor to have the guest user create an "update request object" with each form submit, and have triggers process updates to the original registration and appointment objects referenced by the "update requests".

...or hold the entire multi-object registration transaction in view_state or application cache until confirmed, and do all the related object creates in one transaction.

### PR DESCRIPTION
**Pull request by jhilyard**
# Critical Changes
Remove allowEdit from the Summit_Events_Registrant
permission set. Winter '21 release enforces guest site user
security limiting object and sharing access.

# Changes

# Issues Closed
Fixes #205

### CODE REVIEW

**Comment by jhilyard** [comment]
@tcdahlberg Getting the guest user security conversation started. Right now the master branch can't be used to spin up a scratch org as is. I realize most end users will want the package not the repo contents, but having master broken is not so good. Not having documentation in place to reflect that is even less good - maybe we need a big readme.md header that discusses workarounds to get a scratch org going (comment out the permission set assignment task - should we push that to master?)?

**Comment by tcdahlberg** [comment]
Hi @jhilyard, I'm not experiencing any trouble spinning up a scratch org from master. Are you doing this from the terminal or metecho?

**Comment by jhilyard** [comment]
@tcdahlberg from the terminal, with `cci flow run dev_org --org dev`. I deleted my scratch org, pulled down today's new commits to master, and tried again -- same result. The error message makes sense, the guest user license no longer supports being assigned edit permissions on an object as of winter '21. If it works for you, I wonder if maybe your dev hub has guest user security enforcement opted out and that is transferring to your scratch orgs?

**Comment by jhilyard** [comment]
After pulling in the latest master commits, the feature/205 branch now successfully completes the dev_org flow but the current master branch doesn't for me.
I haven't tested whether these permission changes break any Summit Events functionality, but I'm moving the pull request from draft status because I think it's a higher priority to fix the dev_org flow in master. That will enable the community to bug hunt in scratch orgs and add separate issues where fixes are needed.

**Comment by jhilyard** [comment]
I just did a test registration for each of the two sample events and it worked fine, so if anything's broken by the permissions changes it will require some hunting to find.

**Comment by jhilyard** [comment]
when merging this, please squash merge.

**Review by tcdahlberg — APPROVED** [review]

**Comment by tcdahlberg** [comment]
@jhilyard, this is making sense now. My hub org wasn't spinning up winter 21 for me, but yours obviously was. Merge complte.

Thanks!

**Comment by rdblake21** [comment]
Just added a note of reference that this is not in the v0.11 package.  Installed in a TH Org with Winter '21 and experienced what Jeff mentioned above.  More clarification on what is actually manipulating the record.  I have suspicion that the status is changing within the class and not from the actual user itself.  This would be the same for Appointments. With it built this way, the Guest User is technically only creating the record though from Started, to Registered to Cancelled, it shows that Guest User modified the record.

**Pull request merged**
