### PR TITLE
Aug23 fixes

### LINKED ISSUE #446: [BUG] - Text Area needs to be Text Area (long)
**Describe the bug**
When creating a custom question and utilizing a "picklist" field type, there is a limit of 255 characters because it is a Text Area field.  This limit the number of values you can input, creating challenges when you're wanting to input a list of majors or an extended list overall.

**To Reproduce**
1. Create a Question record and follow appropraite steps for a Custom Question with a Registrant Type of Registrant (though it won't matter)
2. Select "Question Field Type" as Picklist
3. Enter more than 255 characters in the "Picklist Values" field.
4. Try to save the record

**Expected behavior**
Expecting to be able to enter a more extensive list that would be closer 10,000 characters.  Anything beyond that may be looking to better leverage a "Lookup Picklist" now that it's an option.

**Screenshots**
image

**Additional context**
When trying to create a new branch and make the edit to submit as a pull request, I'm unable to change the field type to "Text Area (Long)" because of the reference in the Apex Class (see image below).  The context of the error is:

*There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Cannot change field type of a custom field referenced in Apex class or trigger: "<a href=/01pDP000006HLou">SummitEventsRegisterGuestsController</a>.*

image

### LINKED ISSUE #495: [FEATURE] Additional Questions should be Text Area (Long)
**Is your feature request related to a problem? Please describe.**
We cannot use the Additional Questions Picklist to its full potential, due to the size limits of the field. 255 is too restricting.

**Describe the solution you'd like**
Convert the Text Area(255) to a Text Area (Long) so all users of SEA can freely use the Picklist(s)  

**Describe alternatives you've considered**
For our use-case, Open House events - we intended to use the Picklist to list all our Programs so the registrant may select one of interest. We have too many and the picklist was cut short. Our current alternative is to offer only 1 Program "Undecided" and our recruiters will have to go through the RSVP afterwards and update the records to the correct Program of Interest afterwards.

Question object did not fit our use-case because this simple 1 question being isolated on another page felt bad, from a User-Experience perspective.

**To help determine if a recipe may be more appropriate, please share other use cases, if possible, this functionality would benefit from.**
Any picklist can easily max out after just a few options in the current state. Placing arbitrary limits on # of picklist options because of a field-size in the backend can be frustrating to the end-user. For us, at least, the Additional Questions are only usable for small use-cases and we need to be able to add as many options as necessary for a given event. It's a high-priority item on FIU's side. 

**Are you willing and interested in being engaged during the development and testing process?**
Absolutely - let me know when/where.

### LINKED ISSUE #511: [BUG] Zip Code Triggers an API look-up, which does not always return a City value.
**Describe the bug**
When you type a zip code in on the Registration Page, there is an api request to openstreetmap to grab the related city. But this API does not seem to always return a city value. So "Undefined" is populated into the City field on the form. 

**To Reproduce**

Setup a Summit Event that has the Zip Code field on it. Sample here: https://fiucrm--uat.sandbox.my.salesforce-sites.com/fiubusiness/summit__SummitEventsRegister?instanceID=a1Q7i000005WEpe

Type in Zip: 33187 or 33199 or 34479.. 

**Expected behavior**
I expect a blank value to populate in the City on the form if nothing is returned from the lookup JSON. "Undefined" is problematic. As a user, I dont want to see Undefined or maybe I wont even notice and proceed to checkout with this incorrect city value.
Many of the Florida zip-codes I was trying have this issue. 

We need some error-handling when reading back the JSON :) 

Here is an example:
https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&addressdetails=1&postalcode=33187&country=united%20states

**Screenshots**
image

### LINKED ISSUE #512: When registering for an Event using Preferred Class Year, the registration form gives them impression it is a picklist field, but it is a text field with validation.
**Describe the bug**
When registering for an Event using Preferred Class Year, the registration form gives them impression it is a picklist field, but it is a text field with validation.  Can the "picklist arrows" be removed from the right of the field.

**To Reproduce**
1. Register for an event using Ask Preferred Class Year.
2. Navigate to the question, notice the arrows to the right.
3. See 1 or -1 appear when hitting arrows.

**Expected behavior**
Expect no arrows or anything to indicate a picklist.

**Screenshots**
Attached

**Additional context**
The front end validation on the field is great requiring a class year from 1900 to 2099, but it would be great to remove arrows.  We can provide additional help text in the label or assume the user will figure it out.
Preferred Class field arrows

### LINKED ISSUE #513: [BUG] Add'l Questions Text Box and Text Area are reversed
**Describe the bug**
When configuring Additional Questions, the "Text Box" option creates a Text Area on the template and the "Text Area" option creates an Input field on the template. 

**To Reproduce**
Create a New Event, and populate the Additional Questions 1 .
If you select "Text area required" - the field will be an Input box on the rendered form. 
If you select "Text box required " - the field will be a Textarea on the rendered form. 

**Expected behavior**
I expect a Text Area on the template if I select "Text Area" 
I expect an Input field if I select "Text Box"

**Screenshots**
image
image

**Desktop (please complete the following information):**
Firefox

 

**Additional context**

### LINKED ISSUE #514: [FEATURE] - Guest Registration Screen restrict user from pushing Next when entered Guest Info is not Registered
This is a similar request to issue 502 which helped by turning the +Register Guest button blue once the user enters guest information. We still have concerns that our registrants miss the +Register Guest button and click the Next button without pressing the +Register Guest button. 

I propose that if someone types anything in the First Name and/or Last name that the Next button turns white and is disabled until the registrant clicks the + Register Guest button. At that time the Next button turns blue again. If the user enters another first name and/or last name, the color of those two buttons switch again.

Let me know if you need any additional/clearer details on what I'm suggesting here. We will use customizable text on this screen to help instruct the user to push the +Register Guest button prior to pushing the Next button as a temporary solution. Our registrants are forgetting to push the +Register Guest button with the current configuration.

Thanks for your consideration of this enhancement!

SummitEventsGuestRegButton

### LINKED ISSUE #516: The Event Instance End Time Text and Event Instance Start Time Text fields are displaying incorrectly for a 12 PM appointment.
The Event Instance End Time Text and Event Instance Start Time Text fields on the Summit Event Registration records are displaying incorrectly for a 12 PM appointment.

**To Reproduce**
1. Go to an Instance.
2. Set Instance Start Time and Instance End Time to fall within the 12 PM hour.
3. Navigate to a Registration record.
4. Check on the Event Instance Start Time Text and Event Instance End Time Text fields and see 12 PM represented as 12 AM.

**Expected behavior**
It should display 12 PM as 12 PM and not switch to AM.

**Screenshots**
Please update the formulas to determine AM and PM if it is Greater Than or Equal to 12 it is set to 13 in the package.

IF( HOUR(summit__Event_Instance_Start_Time__c) >= 13, TEXT(HOUR(summit__Event_Instance_Start_Time__c) -12), TEXT(HOUR(summit__Event_Instance_Start_Time__c)))
&
":"
&
IF( MINUTE(summit__Event_Instance_Start_Time__c) < 10 , "0" & TEXT( MINUTE(summit__Event_Instance_Start_Time__c)), TEXT(MINUTE(summit__Event_Instance_Start_Time__c)))
&
" "
&
IF( HOUR(summit__Event_Instance_Start_Time__c) >= 12, "PM", "AM")

### LINKED ISSUE #517: [BUG] Confirmation Page - Total Row Shows Full Balance after Payment
**Describe the bug**
On the SummitEventsConfirmation page (after making a payment), the table showing the event fees is presented to the user which appears to show the full Total Cost (which is confusing - it can be interpreted as the payment was not received)

**To Reproduce**
Successfully make a payment for a Summit Event Instance and you will be taken to a Confirmation Page that shows the same itemized list of fees with the same Total Balance, despite having just made a payment. 

**Expected behavior**
If we are presenting a table on the confirmation page, and we are claiming the Payment is Received, I expect the Total Row to show a $0.00 or the Total Row should say something else like "Payment Received" 

**Screenshots**
image

### LINKED ISSUE #519: [BUG] "This field is required" missing from required Additional Questions on Template
**Describe the bug**
Inconsistent display of required help-text across fields in the event template. 

**To Reproduce**
Pick an Additional Question, and select "text area required" -- when you are viewing the rendered page, you'll see that the little help text does not appear like it does for the regular questions that are also required. 

**Expected behavior**
If field is marked required, I expect the help text to display under all required fields, not only the initial not-additional questions. 

**Screenshots**
image

It seems this additional div isn't included on the additional required questions:

image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox

### PR DESCRIPTION
**Pull request by tcdahlberg**
# Critical Changes

# Changes
- Fixed confirmation page so that if payment is received the balance shows zero
- Formula on Event Instance now shows start/stop time when close to 12
- On the guest registration if the user has entered guest information but has not added that information to the guest list a modal pops up asking "You have unsaved Guest information entered. Select Cancel to finish adding your guests." language for this pop up is configurable via new labels in the event object.
- Additional questions on the event page and on the question object now have an additional long text field for creating longer picklists. This new field can be used in addition to or to replace the old field that was a textarea with 255 characters limiting the pick list.
- Additional label fields were added to the event fee section of the event object to allow for a configurable heading if payment was received or payment was due and an opportunity to add a rich tech description underneath the heading.
- Various bug fixes

# Issues Closed
- Closes #517 
- Closes #516 
- Closes #514 
- Closes #513 
- Closes #512 
- Closes #511 
- Closes #495 
- Closes #446
- Closes #519

### CODE REVIEW

**Comment by tcdahlberg** [comment]
I am still testing through a throw away package version in conjunction with a gateway to make sure payments flow through when a gateway is set up. All the above can be test through without a gateway though.

**Comment by tcdahlberg** [comment]
I tested the a feature/throw away package in my touchnet project and the package worked as expected.

**Comment by rdblake21** [comment]
✅ #446 
✅ #495 - Updated Page layout and pushed to PR
✅ #511
⚠ #512  - This works, but the error leaves no context.  Please add "Please enter a valid 4-digit value" @tcdahlberg @walt0019 
✅ #513 
✅ #514 
✅ #516 
☑ #517 - Unable to test based on payments process @tcdahlberg 


@tcdahlberg All bug testing passed, but I made a note above on #512.  please review and let me know if you have questions.

**Comment by tcdahlberg** [comment]
@rdblake21, I added the error message you suggested to the preferred class year question.

**Comment by rdblake21** [comment]
@tcdahlberg Thanks for the update. Looks good, but I think we need to update the logic.  Right now, the error message only shows for "Ask and Require", but if the question is set to "Ask", the error doesn't display at all.  We should always have the error context to ensure data quality and an explanation, even if we don't require it.  The "Ask" should operate as it does now, clearing out the error field, but highlight in red and show the error message (like Ask & Require does), but then should the registrant not enter a value, they should be able to continue with a blank value, which is the current experience. 

So the only item to update is that ANY time the Preferred Class Year is asked, it should always reflect the error message.

I would update the apex, but I'm not sure how to do it as it isn't an IF statement anymore. I don't know that we need the logic based on the field value as the error should just show.

image

**Comment by tcdahlberg** [comment]
@rdblake21, I almost pushed back on the preferred class year requirement because technically it is a new way to display help text and required some work. Short story, I went ahead and made it.

Most of this validation is done on front-end javascript so it's not really in the visualforce page. validYear is a particularly heavy validation since it validates on key down and on change. I didn't like the look of it being required, so I built out a semi-error state for not required called slds-has-info. When not required this will show the help text and bold the outline of the input. 

image

There is a lot of hard code "This field is required" on the page. We should probably create a default label for the required field and let the event manager choose what that says. Next release?

I also fixed #519 because I was in that code and it was an easy win.

**Comment by rdblake21** [comment]
@tcdahlberg This all looks really good and I agree with you on the user experience for something that's not required.

I hear what you're saying on the default label for a required field, however, I don't know that we've had feedback on it being an issue.  It seems relatively standard, IMO, and there is additional custom error handling on the Custom Questions object.  Please disagree with me, but I'm hesitate to create an issue and another field label when we have functionality to drive individuals to creating custom questions.

**Review by rdblake21 — APPROVED** [review]
Tested and reviewed.  All comments are in the conversation.  Ready to merge into Main branch

**Pull request merged**
