### PR TITLE
Feature/admin calendar

### LINKED ISSUE #261: Admin Calendar (based on BYU functionality)
From: Matthew Gardiner
Sent: Friday, December 11, 2020 4:37 PM
To: Jim Hubert; Dahlberg, Thaddaeus B.
Subject: Re: [External] Summit Sprint
 
 would love to help get an admin calendar into Summit Events. It's pretty basic at this point. It simply allows you to see any Summit Event Instances, or instances that you own (when you click that button) via the owner custom property on a Summit Event Instance. There may be a better way to do that such as a one-to-many relationship instead of a one-to-one. You can drag and drop calendar events to change their time or length and that's pretty much it. I built a new Apex controller around the functionality but I suspect a lot of it is pretty similar to the Summit Events Feed class but I wanted to separate the controllers for public vs private access.

The real magic is that when you're doing AJAX to a Salesforce controller page, you can send an authentication header from the JavaScript including an authentication token that makes the Apex class treat the AJAX request as the currently logged in user. If you're using the browser native XMLHttpRequest that looks like this:

 xhttp = new XMLHttpRequest();

 xhttp.setRequestHeader('Authorization', 'Bearer {!$Api.Session_ID}');

I'll work on getting a github repository clone set up sometime next week. I'm not super familiar with github so I've been hesitant to do too much there. There are some byu specific paths that will have to be made generic I'm assuming by getting url paths in a more dynamic way.

Thanks,
Matt Gardiner

From: Jim Hubert <jim.hubert@fdnpartners.com>
Sent: Thursday, December 10, 2020 11:58 AM
To: Dahlberg, Thaddaeus B.; Matthew Gardiner
Subject: Re: [External] Summit Sprint
 
Matt and Thad,

Hope the two of you have had a chance to connect to discuss this, I agree that this calendar would be great to have in the Open Source version!

Jim Hubert  | Foundation Partners  |  763.232.1758  |  jim.hubert@fdnpartners.com 

From: Dahlberg, Thaddaeus B. <thad.dahlberg@stthomas.edu>
Sent: Thursday, December 3, 2020 2:14 PM
To: Matthew Gardiner <Matthew_Gardiner@byu.edu>; Jim Hubert <jim.hubert@fdnpartners.com>
Subject: RE: [External] Summit Sprint
 
Hi Matt,

That is a very cool calendar. We should get that in to the open source version!

There is currently no user relationship wired into the instances, but it is a good idea. Hanging off the instances there is a host object that is poorly implemented. We used it in the UST Events version to apply hosts to appointments. Like when we would have overnights the dorm host would be applied to the overnight appointment, or lunch would have the host of the person who you were going to eat lunch with at the event. It definitely needs to be architected better and perhaps we could add the event host into the mix. The trouble is where all these hosts live. Are they elevated to an equal level with the event objects so all objects can get at them. Perhaps I’m being confusing.

Let me know if you want to take some time to talk through some ideas.

Thanks

Thad

From: Matthew Gardiner <Matthew_Gardiner@byu.edu> 
Sent: Thursday, December 3, 2020 1:35 PM
To: Jim Hubert <jim.hubert@fdnpartners.com>; Dahlberg, Thaddaeus B. <thad.dahlberg@stthomas.edu>
Subject: [External] Summit Sprint

Hello,

I have a question that I'm hoping someone with a little more Salesforce experience can answer. I built a calendar that allows administrators to drag and drop event instances to reschedule them (or click them to go to the instance edit page). I've been asked to create a feature that takes the currently logged in user and only shows them events for which they are marked the host (the 'My Events' button in the screenshot below). The way that I've accomplished this is by having a lookup field on Instances to the User object called 'Owner' that a Salesforce user can set when creating/updating the instance. If there is a better way to do that without using a custom field I'd love to know. On initial inspection I didn't see any other relationship or object that served that purpose. In our case hosts for events will almost always be Admissions outreach folks and one of them spearheads the event even if other presenters are involved.

​Thanks,
Matt Gardiner
BYU Enrollment Services

### PR DESCRIPTION
**Pull request by GardinerMatt**
# Critical Changes

# Changes
Adds SummitEventsCalendarSubscription object
Adds Summit Events Calendar (admin calendar) tab
Adds trigger and validator to prevent null or duplicate calendar subscriber
Adds trigger to automatically add calendar subscription to instance
Adds custom setting to allow toggling of automatic calendar subscription
Adds basic tests for new components

# Issues Closed
#261

### CODE REVIEW

**Comment by rdblake21** [comment]
Created this branch on this project so it could be tested in Metecho.  This branch is also updated with the main branch and was able to spin up a scratch org.  Tab is included, which is great!

[AdminCalendar_SEA_Branch](https://github.com/SFDO-Community-Sprints/Summit-Events-App/tree/AdminCalendar_SEA_Branch)

@GardinerMatt do you have additional documentation as it pertains to functionality and expectations for the calendar?

**Comment by GardinerMatt** [comment]
@rdblake21 I don't really have anything by way of documentation. Our Admissions department wanted an easy way to see their upcoming events and drag and drop them to resize or reschedule them. The calendar tab facilitates this by using a FullCalendar instance with a custom controller. There is a custom object (CalendarSubscription) that is a related item on the SummitEventsInstance to indicate that a specific user wants to track a given event on their calendar. Additionally there is a custom hierarchy setting that determines if a calendar subscription should automatically be made when a user creates a new instance.

I kind of wrote this up in a rush and I'm not certain if it would pass a security review. I'm passing a token around in JavaScript. I would probably rewrite this to be a LWC now that I'm more familiar with them but I think that would be a non-trivial amount of work that I probably don't have time to commit to right now. Let me know what you'd like to do with this long-term if anything.

**Comment by rdblake21** [comment]
@GardinerMatt Thank you!  This is what I was looking for!

We are currently testing functionality and I appreciate you notes on what you're doing.  We've been doing a lot of security review lately, so this will be a part of it, but wanting to ensure we understand functionality first.

Thanks for contributing it back to the project!

**Comment by GardinerMatt** [comment]
I forgot to mention that a short click will take you to the event instance record page. So long click = move, resize. Short = go to instance.

**Comment by rdblake21** [comment]
Hey @GardinerMatt!  I wanted to reach out again about this development.  I recently learned that you can Calendar Anything with the native Calendar tab in Lightning. An individual needs access to Calendars and then can create a "New Calendar", select the object they desire and set the start and end date, reflecting events they choose based on their setting.  

The filter or select of what appears is based on a List View filter.  So as long as individuals can update/manage their own list views, they can have a calendar, with various views, overlapping filters, etc with native salesforce functionality.

Similar to what I experience and what you explained above, you can long click and drag to update the date as wel las short click to get to the specific record.

In this instance, you can create a calendar on the Summit Event Instance Object, Select the Start Date/Time and End Date/Time in addition to also selecting a specific list view for additional filtering and selecting the appropriate title to display on the calendar. This will reflect the desire instances in an Admin based view with functionality that allows for adjustments without clicking into the record itself.  Access is then based on access to the list view, record level access based on Sharing Settings/Rules as well as object level access. Normal sharing settings would apply as well.

From my assessment, what you built is able to be handled by the native Salesforce functionality and allows Salesforce to handle the management of the calendar.  Based on that, I don't believe we want to incorporate this into the package since it would be redundant functionality and require additional effort to maintain when users have the ability to leverage native functionality for similar results and experiences.

Let me know if you want/need a demo of this.  The first part of this Trailhead highlights the functionality of Object Calendars - https://trailhead.salesforce.com/en/content/learn/modules/sales_admin_maximize_productivity/work_smarter_calendar_events - While this is in a Sales aspect, you can do the same things for a visit team wanting to appropriate plan for upcoming events.

**Comment by GardinerMatt** [comment]
Hi Blake. We've used the native calendar for a number of issues and found it to not be very robust. In fact I've had to write custom LWC's to get around some of the limitations that the native calendar has. However, I totally agree with you that this isn't worth maintaining and that native functionality should be used where possible. I'm going to close this pull request. Our own Admissions department has gotten along just fine without this feature. We've been trying to run this SEA as vanilla as possible. BTW, I heard about passing the security review. Congrats! We're excited for the future of SEA.

**Pull request closed without merging**
