### PR TITLE
Payment pageflow

### LINKED ISSUE #487: [BUG] Event feed close before days not working
**Describe the bug**
If event is set to close before a certain amount of days the SEA REST API feed does not reflect that numbered closure correctly. The feed needs to use the new isEventClosed method in the shared class. This will use the formula field on the instance that calculates close time and date rather than the inline code in the feed that is currently being used.

### LINKED ISSUE #489: [Help Text] Help text wording structure
**Describe the bug**
The help text for the Event Name field. should be updated to read a bit clearer.  Change FROM Name of event and displays on registration page  TO Name of the event that displays on the registration page.

HelpTextConfusing

### LINKED ISSUE #490: [Help Text] Type-o in Help Text for Private Event checkbox
The word display is missing the "L".
HelpText-typeo

### LINKED ISSUE #494: [FEATURE] Location Filter for "Location Type Override"
**Is your feature request related to a problem? Please describe.**
We are only able to filter event instances based on the main Event record's location. We are offered a Location Filter but it only works at the Event-level. For example, we cannot filter Online instances of an Event if the Event is initially On-Site.

**Describe the solution you'd like**
Ideally, we would like to be able to filter by location at the instance levels so the JSON returns the subset of instances in a certain location.

**Describe alternatives you've considered**
Creating different events for each location would alleviate the issue but then that defeats the purpose of the "Override" feature in Event instances!

**To help determine if a recipe may be more appropriate, please share other use cases, if possible, this functionality would benefit from.**
This would benefit all users that use the eventFeed JSON and want to make use of the flexibility provided by the Location Override fields.

**Are you willing and interested in being engaged during the development and testing process?**
Absolutely, please loop me in as necessary.

### LINKED ISSUE #497: [BUG] Checkbox for "Registrant Receive Texts" appears as required even if the Phone field is optional.
**Describe the bug**
Checkbox for "Registrant Receive Texts" appears as required even if the Phone field is optional.

**To Reproduce**
Add Phone to RSVP page, option "Ask Mobile"
image

**Expected behavior**
At a minimum, _if_ someone enters a number in the Phone field, _then_ the"Registrant Receive Texts" should appear, and be required. 

Ideally, it would be nice to maybe toggle that checkbox related to Phone Numbers. 

**Screenshots**
bug1

### LINKED ISSUE #499: [BUG] External payment page not working in payment page flow.
External payment page not working in payment page flow.

### LINKED ISSUE #502: Guest Registration functionality needs to be more user friendly.   I have suggestions on how to make this screen better.
**Describe the solution you'd like**
I have an event/instance configured to allow for guest registrations.   Currently our registrants miss the **_+Register Guest_** button and they click the **Next** button as it is more prominent and BLUE.   See link below for screen shot.

I propose that if someone types anything in the First Name and/or Last name that the **+ Register Guest** button turns blue and the **Next** button turns white and is disabled until the registrant clicks the **+ Register Guest** button.   At that time the **Next** button turns blue again and the **+ Register Guest** button turns white again.   If the user enters another first name and/or last name, the color of those two buttons switch again.

Let me know if you need any additional/clearer details on what I'm suggesting here.   We need this new enhancement completed before we can start using this new guest feature.   Our registrants are getting confused on what to click on with the current configuration.

Thanks for your consideration for this enhancement!

image

### LINKED ISSUE #504: [BUG] Capacity Control doesn't respect hosted registrants
On the instance when "Capacity Control" is set to "Individual Registrants" while utilizing the ability for registrants to create their hosted guest registrants the capacity number does not reflect that hosted registrants are not individual registrants.

### LINKED ISSUE #505: [BUG] Email field inserts don't respect namespace
When inserting email fields like add to calendar into SEA transactional email the namespace summit__ does not work correctly and needs to be omitted just for email links. These fields should follow the same namespaced field API names as all the other registration fields.

### LINKED ISSUE #506: [FEATURE] Use secure, site strict cookies
Since Salesforce's cookie creating method now allows for secure cookie creation with strict same site rules SEA should switch the main encrypted cookie to a secure cookie. The current cookie is still secure because all data in it is AES256 encrypted, but since browsers are preferring secure cookies lately we should switch.

### PR DESCRIPTION
**Pull request by tcdahlberg**
# Critical Changes

# Changes
- Rest API event feed uses shared class for determining the closing of an event. Close even before ** days now works correctly in the feed.
- Typos fixed in field help text.
-  Rest API event feed now takes a new parater of location type (locationtype) that filters events on the location type set on the event or the override on an instance of the event.
- A new checkbox on event labeled "Do not show receive text question" suppresses the question about receiving text when phone numbers are set to be asked of registrant.
- Payment page, when set, now works correctly in the page flow of registrations and will jump out of the package to an external, user created page for payment processing.
- The button to add guest registrants on the Guest Registration page now turns blue when a user adds any information to the guest registration form. This will help mitigate missing that button.
- Hosted registration are now not counted as primary registrants when capacity control is set to only count individual registrants.
- Link fields on registration (think add to calendar) now respect the namespace when used in transactional email, api-name, field merge functionality (incidentally they still respect non-namespaced field merge api names even when namespaced).
- Summit Events App now uses secure, strict site cookies to maintain encrypted data to preserve registration information to the guest user.

# Issues Closed
- Closes #487 
- Closes #489 
- Closes #490 
- Closes #494 
- Closes #497 
- Closes #499 
- Closes #502 
- Closes #504 
- Closes #505 
- Closes #506

### CODE REVIEW

**Comment by rdblake21** [comment]
@tcdahlberg only have one question below on #494 

Testing notes:

🔑 https://github.com/SFDO-Community/Summit-Events-App/issues/487 (unable to test)
✅  #489
✅ https://github.com/SFDO-Community/Summit-Events-App/issues/490

❓ [FEATURE] Location Filter for "Location Type Override"  #494
- Should this reflect the options within the picklist, similar to Building?
image

✅ https://github.com/SFDO-Community/Summit-Events-App/issues/497
🔑 https://github.com/SFDO-Community/Summit-Events-App/issues/499 (Unable to test)
✅ https://github.com/SFDO-Community/Summit-Events-App/issues/502
✅ https://github.com/SFDO-Community/Summit-Events-App/issues/504
> Documentation will want to reflect that Allow Other Attendees and Max Other Attendees and Guest Registration (the entire tab) are separate and may impact capacity.

> image

✅ https://github.com/SFDO-Community/Summit-Events-App/issues/505
> Will want to test more thoroughly in the managed package


🔑 https://github.com/SFDO-Community/Summit-Events-App/issues/506 (Unable to test)

**Comment by tcdahlberg** [comment]
@rdblake21, good call on the parameter key location type needing the options listed. I've added that to the code now. Thanks!

**Comment by rdblake21** [comment]
✅ [FEATURE] Location Filter for "Location Type Override"  #494

**Review by rdblake21 — APPROVED** [review]
tested all appropriate changes and made formal comments.  Things look good and additional testing when repackaged will be required per usual

**Pull request merged**
