### PR TITLE
2024 jan fix before release

### LINKED ISSUE #526: Increase field size on "Number of Guests" field on Summit Events Registration to 3 digits
On the 'Summit Events Registration' object the "Number of Guests' field is currently 2 digits long.  I am working with a school that is using Summit Events to register all seniors for a high school to visit which have more than the 99 possible guests the product currently allowed, so they are having an error message saying "number of guests outside of valid range for numeric field: 145" when they try to register 145 guests.

I believe the best solution is to update the field length field for the Number of Guests field from 2 to 3 digits, this will allow up to 999 guests to be added to a registration.

### LINKED ISSUE #531: Relabel or update the Preferred First Name Formatted field.
User believe the Preferred First Name Formatted field should display the Preferred First Name field if provided or the First Name field.  Users are not expecting the Last Name of the registrant to also be included.

Suggestions to resolve the issue

* Relabel the field to be Preferred First Name Last Name Formatted.
* Or keep the field labeled as is, but update the formula to remove Last Name.
* Gauge interest if two formula fields (one first name field formatted should be provided as well as the first name formatted with last name should be provided within the package. 

Recently added Help Text, "This includes Preferred First Name if provided AND Last Name." so end users could understand.

### LINKED ISSUE #540: [BUG] - Blank Submit Page w/ only Custom Questions (no Guests)
**Describe the bug**
When creating an event, there is an additional page that's blank, which creates an extra click and an awkward flow to the registration process.  I anticipate that when the admin uses a combination of standard and custom questions, only being asked to the registrant, that they go from the CustomQuestions page directly to the Confirmation Page as the submit page has nothing to review.

The submit page offers review of Guests, Appointment, Donations, Fees, so if those are not  in the event structure, the page should get skipped.

**To Reproduce**
1. Create an event using standard questions
2. Create a custom question record for the Registrant
3. Register for the event and see that you have 4 pages in the page flow (register, customquestions, submit, confirmation)

**Expected behavior**
If there are no guests, appointments, fees, or donations skip straight to the confirmation page. 

So Register-->Custom Question--->Confirmation

**Additional context**

### LINKED ISSUE #542: [BUG] Transaction email invocations limit reached on mass update of registrations
**Describe the bug**
Transactional emails are being sent in a for loop in the registration trigger code resulting in a "Too many API email invocations" error. Currently only 10 emails are allowed to be sent during one transactional event. The error and solution are defined here:

https://help.salesforce.com/s/articleView?id=000385111&type=1

**To Reproduce**
1. Set up transactional emails to a status
2. Mass change 11 registrations status to match the transactional email status

**Solution**
"Bulkify" the email message into a list and send with one sendmail as described in the link above.

### LINKED ISSUE #543: [BUG] SEA Visualforce Pages for Digital Experience
**Describe the bug**
Currently you are unable to include most of the Summit Events App Visualforce pages on a Digital Experience Site.

**To Reproduce**
1. Go to a Digital Experience Site
2. Try to add a Visualforce Page to an Experience Site page

**Suggested Fix**
Visualforce pages will not be available for Digital Experience unless the pages metadata includes the availableInTouch set to true:
```
<availableInTouch>true</availableInTouch>
```

### LINKED ISSUE #544: [BUG] - Mobile Calendar not Clickable
**Describe the bug**
(https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007W6ymlSAB)
Error message is happening when attempting to click on any of the events to view its details. It is only happening for mobile screens, on desktop and phones.

The events are pulling correctly, but when we click on the event, nothing loads. The registration page should come up.

**To Reproduce**
1. Open the standard OOTB Calendar on a mobile device or reduce window
2. Try to click on an open event

**Expected behavior**
Regardless of the view, the event is clickable and someone can get to the registration page.

**Screenshots**
image (4)

**Desktop (please complete the following information):**
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - Browser: Safari

### PR DESCRIPTION
**Pull request by tcdahlberg**
# Critical Changes

# Changes
- Summit Events App (SEA) calendar view now has a link wrapper around the event descriptions needed when view goes into mobile list mode to be clickable.
- All Visualforce metadata is set to availableInTouch = true to facilitate embedding of pages in Digital Experience sites.
- Triggered transactional emails are now bulkified meaning all triggered emails send at once per batch. This may or may not alleviate the  SINGLE_EMAIL_LIMIT_EXCEEDED error when triggering more than one status change on registrations when that status evokes an email. Scratch org testing was inconclusive. 
- The page progression now detects if there is only the Registration page and the Additional Question Page in play and progress to the confirmation page (eliminating the blank Submit page). The button at the bottom of the Additional Questions page will switch to "Register" rather than "Next" as well.
- Preferred First Name Formatted field relabeled to Preferred Full Name Formatted.
- Amount of guest that can be submitted is now a 3 digit Integer field to allow for up to 999 guests. There may be a theoretical limit to how many guest a registrant can actually enter at once.

# Issues Closed

- Closes #544
- Closes #543 
- Closes #542 
- Closes #540 
- Closes #531 
- Closes #526

### CODE REVIEW

**Comment by rdblake21** [comment]
✅ https://github.com/SFDO-Community/Summit-Events-App/issues/544
✅ https://github.com/SFDO-Community/Summit-Events-App/issues/540
✅ https://github.com/SFDO-Community/Summit-Events-App/issues/531
✅ https://github.com/SFDO-Community/Summit-Events-App/issues/542 - Was able to do this with 15 changed registrations and I received 15 emails.

All the above were tested and worked as expected or anticipated



🟨https://github.com/SFDO-Community/Summit-Events-App/issues/543

@tcdahlberg while this is working, there is some functionality challenges.  When I add it to the page, when you hover, the short description appears to attach to the mouse over and then stays.  Not sure what's going on there.  So, working with some bugs in it.

image


🟨https://github.com/SFDO-Community/Summit-Events-App/issues/526

@tcdahlberg for consistent, the field value should really be 4.  The fields that would impact this have a 4 digit limited... see image below (Guest Max Amount is also a 4 digit field).

image

**Comment by tcdahlberg** [comment]
@rdblake21 , I increased the Number of guests to 4 digits for consistency. I tested the visualforce page usage on a lighting layout and a Digital Experience Site and did not have the negative results you did. Which type of Digital Experience site template did you use? I used the aura based one rather than the LWR.

image

**Comment by rdblake21** [comment]
✅ https://github.com/SFDO-Community/Summit-Events-App/issues/543

@tcdahlberg I retested and found that the issue I was having was in the Builder and during the Preview. When published the site and then went into it as a customer/client would, it worked as you have reflected and what I expected.  So we're good on this one and in the release notes, we're capture the known experience.

✅ https://github.com/SFDO-Community/Summit-Events-App/issues/526

@tcdahlberg Sounds good!

**Review by rdblake21 — APPROVED** [review]
Reviewed all pushed items and tested them. Conversation captures these aspects.  Approved to merge into the Main branch

**Pull request merged**
