### PR TITLE
Itineraries

### LINKED ISSUE #86: Developers - Itinerary generation in base package
During the recent removal of EDA dependency in the project TDTM triggers needed to be removed. One of these triggers was responsible for generating requested and confirmed itineraries. Both generated off of appointments selected during registration. Requested happening on the status of "Requested" on the registration and confirmed itineraries on the confirmation of each of those appointments.  It may be possible to use a lighting flow with APEX actions to achieve this without creating triggers and a framework for those triggers.

## Possible enhancement ##

What appears on an itinerary comes off of the appointment object for the registration. What appeared in the generated itinerary was often debated and changed per event. Perhaps we could fulfill all requests with a simple template field on the umbrella event record. The template could reference any field that is on the appointment record (similar to how transactional emails are created with the registration record). A template could look something like this:

> Heading 1 | Heading 2 | Heading 3
> Appointment_Field__c | Appointment_Field__c | Appointment_Filed__c

The top line could be plain english headings with pipe separators. The bottom line could be field API names from the appointment object.

### LINKED ISSUE #372: Instance Short Description on Calednar
When reviewing the calendar in Summit Events, the Instance Short Description isn't appear on the hover over. It was my understanding that the Instance Short Description is utilized for the calendar so there is some detail in addition to the Instance Title.

### PR DESCRIPTION
**Pull request by tcdahlberg**
# Critical Changes

# Changes
- Created an itinerary trigger that produces a  list of requested appointments and a separate list of confirmed appointments
- Created fields to control what appointment object fields appear on the confirmed itinerary
- Created fields to control headers for selected appointment object fields for generated confirmed itinerary
- Embedded full calendar pop-up uses instance description first then event description if that does not exists

# Issues Closed
- Closes #86 
- Closes #372

### CODE REVIEW

**Comment by rdblake21** [comment]
Testing Notes:
Made sure that Appointment Types were created, created an email with Generated Itinerary and Generate Requested Appointments were in email.  
* Created a registration and received email with Requested Appointments in an itinerary ✅
* Reviewed the Registration record and Requested Appointment look good! ✅


Error Received - @tcdahlberg 
* When trying to change an Appointment in a "Requested Status" to "Confirmed, I received a Trigger Error:
image

**Comment by rdblake21** [comment]
Functionality Not working on Auto Confirm Appointment - @tcdahlberg 
Appointment Type is set to "Auto Confirm Appointment"
image

When the Registration was received with the appointment, the status is set to Registered:
image

The expected behavior is as follows:
* If the Appointment Type has the field "Auto Confirm Appointment" set to True
* When the registrant selects the appointment (where the appointment type is set to Auto Confirm Appointment as true), when the appointment record is created, it should have a status as "Confirmed".
* The Confirmed Appointment should be reflected on the "Generated Itinerary" as well as the "Generate Requested Itinerary" fields.

**Comment by rdblake21** [comment]
Issue/Error - @tcdahlberg 
* When I tried to add my own value of "Status" with an API value of "Status__c", The generation of itineraries stopped all together.
* I turned on debug and there were not noticed errors (from what I could see).
* This occurs regardless of the value being utilized.  It's almost as those the new value breaks the entire global picklist value set.
* Things I did notice in the debug:
>* 03:46:09.0 (260240889)|VARIABLE_ASSIGNMENT|[198]|packagedItineraryFields|"List of size 15 too large to display"|0x4da6b496
>* 03:46:09.0 (342886101)|EXCEPTION_THROWN|[61]|System.QueryException: No such column 'Status__c' on entity 'Summit_Events_Appointments__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
> Error was in the field.  The field is called "Appointment_Status__c" - Fixed this error, but not as fruitful as I'd hope...

When Adding a Custom fields of appropriate value (Appointment_Status__c), I get the same issues as above, but the debug log says:
* 03:59:18.0 (273573907)|VARIABLE_ASSIGNMENT|[209]|PicklistValues|"List of size 16 too large to display"|0x1b283904
* 03:59:18.0 (277994694)|EXCEPTION_THROWN|[61]|System.QueryException: duplicate field selected: Appointment_Status__c
* 03:59:18.0 (278095696)|HEAP_ALLOCATE|[61]|Bytes:51
* 03:59:18.0 (278285636)|VARIABLE_SCOPE_BEGIN|[64]|e|Exception|true|false
* 03:59:18.0 (278418035)|VARIABLE_ASSIGNMENT|[64]|e|"common.apex.runtime.impl.ExecutionException: duplicate field selected: Appointment_Status__c"|0x2f8ae292
* 03:59:18.0 (278426279)|STATEMENT_EXECUTE|[64]
* 03:59:18.0 (278428605)|STATEMENT_EXECUTE|[65]
* 03:59:18.0 (278510967)|HEAP_ALLOCATE|[65]|Bytes:47
* 03:59:18.0 (278545748)|USER_DEBUG|[65]|DEBUG|duplicate field selected: Appointment_Status__c
> There is not a duplicate field as I added Appointment Status and it wasn't in the list before.

Tried adding a different field:
* Having the same experience as above in that nothing generates and seems to error:
* Tried adding "Sort_order__c" and unable to get anything to generate.

Using all 5 Itinerary Fields:
* When Nothing is selected on the Event record for "Itinerary Display Options" - the Generated Request Appointments seems to only be pulling in 4 fields, not all 5
* When "Labels as headers" is the value for "Itinerary Display Options" - the Generated Request Appointments seems to only be pulling in 4 fields, not all 5
* When "Labels as headers" is the value for "Labels inline with colon" - the Generated Request Appointments seems to only be pulling in 4 fields, not all 5
> With all of the above there was no change in style in the email or on the Registration record. Tried with only 4 headers/Titles and no change either.

**Comment by rdblake21** [comment]
Additional Testing:
* Short Description on calendar looks good! ✅
* @tcdahlberg Verified Page Flow that if all are Auto-Confirm Appointment, the appointment page and submit page is bypassed, but there is an issue with the logic.  If all Appointment Types are set to "Auto Confirm Appointment", the appointment page is bypassed, regardless of the chosen state or registrant input requirements.  The page should be bypassed ONLY if all are set to "Auto Confirm Appointment" are all TRUE and all Appointment Types have a chosen state of "Added and Required".  If there are any Appointment Types that have a registrant input (required or not), the page should not get skipped. 
> there are use cases where all appointment types may need to be set to Auto Confirm Appointment, but the registrant should still be able to select their own options and/or have user input.

* @tcdahlberg Not seeing Account on the feed or ParameterKey
 > https://force-app-6091-dev-ed.scratch.my.salesforce-sites.com/services/apexrest/summiteventsfeed?feedType=parameterkey
> https://force-app-6091-dev-ed.scratch.my.salesforce-sites.com/services/apexrest/summiteventsfeed?eventId=a0B8F0000003yVt&feedType=eventList&viewStart=2023-1-7+00:00:00&viewEnd=2023-3-9+24:59:59
> image

**Comment by tcdahlberg** [comment]
Thanks for testing @rdblake21, 

The following fixes have been addressed with the latest round for branch updates:

- Fixed the trigger error by checking whether the itinerary display options were set before accessing that field. 
- Fixed auto confirmed status by moving the default "Registered" status before applying the conditional "Confirmed" status.
- Possible fix for custom fields being added to the global value set for appointment fields. I Did multiple verifications in the code to make sure the field did exist on the object before allowing it to become part of the query. Adding my own filed worked for me.
- Fixed the page flow issues on appointments auto confirmed and set to be shown by updating getPageFlow method query.
- Account has been added to the feed parameters. Incidentally, school= is also an available parameter that works the same as account to maintain UST compatibility, but I'm not advertising that in the feed parameter keys to avoid confusion.

**Comment by rdblake21** [comment]
- ✅ **Parameter Type feed** is showing account and functions as expected 
  - ❓ Should the Parameter Feed reflect the options available if Events have values in the list
- ✅ **Auto Confirm Appointments** - When Appointment Type is set to Auto Confirm, it's creates with a Status of Confirmed 
- **Page Progression Logic** ⛔
  - If I have all Appointment Types Set to Auto Confirm and the Chosen State is Blank on all Appointment Types, the page is getting skipped. Same for is non of them are Auto Confirm and Chosen State is blank... page is getting skipped. If one is set to Auto Confirm as TRUE, they page appears.  Logic seems to have some issues and dependency on the status.
  - Logic should be something to the following:
  > If (Auto-Confirm is True AND (Chosen State is "Added and Required" OR "Added but not shown") for ALL APPOINTMENT TYPES, Skip the page. If Chosen State is blank on any of the appointment types regardless of any other settings on Appointment Type, the Appointment Page should show. 
  >Logic needs to reflect that if there is an appointment that can be chosen, the page should appear, even if it will confirm.  As I think more about it, Auto Confirm shouldn't really impact the page progression, only the Chosen State should impact it as the page is presented for the registrant to engage with, which has not status impact until they engage with it.
- **Itinerary Settings - Item Display Options** ⛔
  - The Display option is working for the Generated Itinerary field, but the Requested Appointment Field doesn't change. These should match one another. Collectively, they seem to be operating differently, but I was expecting them to operate the same and be controlled by Status as to which appointment is reflect where.
  > image
- ✅ **Itinerary Settings - Custom Field & Picklist Addition**  Was able to add a field as well as create a custom field and have it appear on the Itinerary. This is most impactful for the Itinerary AFTER the registration happens as there is some limitation as to what can be on the Requested Appointments since it needs to feed from the Appointment Type to the Appointment through the packaged trigger.

**Comment by rdblake21** [comment]
- ✅ Page Progression Logic - Tested a combination of scenarios with appointment types in different chosen states and auto confirm being true.  The testing passes the logic, but want to be mindful that the logic does not include any reference to "appointment limits".  In the scenario, there could be an appointment limit of 2, but the appointment is selected as Added and Required.  I can't think of a use case where this would be impacted as you wouldn't proactively add something to a list that can be added multiple times. Also, if there is something that you can add multiple times, there will likely be registrant input, so again, you wouldn't proactively add it, you'd leave the chosen state as blank.  Because the use case is missing, we don't need to update the logic to be considerate of this and we should document it how the functionality works. We could also add validation on the back-end to ensure users don't configure appointments in this way.

**Comment by rdblake21** [comment]
- ✅ Itinerary Settings - Item Display Options - Based on a conversation, this is not an error.  The Requested appointments is hard coded capturing three primary fields that the registrant experienced and/or engaged with. There is no formatting options as no headers/labels can be clearly identified.  This is the MVP and supported by daily users. The Generated Itinerary field is what is adjustable as it can be User defined.

**Comment by rdblake21** [comment]
Review all issues on testing and all have passed my assessment and working as expected.  Going to add a review and merge to master for further testing on the package. @tcdahlberg

**Review by rdblake21 — APPROVED** [review]
Did significant testing and review all aspects of the PR. Functionality is working as expected and no additional errors have been caught in my review.

**Pull request merged**
