### PR TITLE
April fix before packaging

### LINKED ISSUE #395: Enhancement: Ask Mobile and Ask Require Mobile options within Ask Phone field
**Is your feature request related to a problem? Please describe.**
Feedback from the May 2022 Sprint, expected a Ask Mobile and Ask Require Mobile options only.  This request is probably focused from a higher ed, younger demographic perspective, but good call out that most people only operate from a Mobile phone perspective and we should simplify the form data gathering.

**Describe the solution you'd like**
Add additional options, Ask Mobile and Ask Require Mobile, and drive experience on the SEA Registration Page.

**Describe alternatives you've considered**
The form functions today with the Home and Mobile options, but could require, limit and simplify options if there were Mobile only options.

**Are you willing and interested in being engaged during the development and testing process?**
Yes and add Robert Wynter.

### LINKED ISSUE #464: [BUG] - Hardcoded values on the Submit Page
**Describe the bug**
The Submit page currently has hardcoded values that should read the labels/headers of their respective pages. Currently it's hardcoded as Appointments, which  may not meet all use cases.

**To Reproduce**
1. Create a normal event with appointment types and Guests
2. Create a new registration and get to the submit page.
3. You'll see the header are hardcoded and don't match the respective page headers.

**Expected behavior**
I had expected they'd match so if the term Appointment wasn't being utilized, it would reflect what was chosen for that page when setting up the event.

**Screenshots**
Line 86 and line 108 on the SummitEventsSubmit.page need to be updated to have fields that are dynamic content. This is the screen shot of me changing the hardcoded label.
image

**Additional context**

### LINKED ISSUE #467: The Registration Page errors when an Appointment Type has a picklist with only one value.  IE, the Appointment Category only has one Appointment Type value tied to it.
**Describe the bug**
The Registration Page errors when an Appointment Type has a picklist with only one value.  IE, the Appointment Category only has one Appointment Type value tied to it.

**To Reproduce**
1. Go to Appointment Types and create an Appointment Type record with an Appointment Category that only has one or zero associated values to the Appointment Category.
2. Now start a registration for the Event Instance.
3. When a user gets to the Appointment Type registration section, the page errors.

**Expected behavior**
An admin user creating the event would expect an error when creating this Appointment Type or some indicator that there is an issue before registrants would see this. 
-

### LINKED ISSUE #468: Ask mobile and require as part of the Ask Phone question.
**Is your feature request related to a problem? Please describe.**
Ask mobile and require as part of the Ask Phone question.  At this point, students have phones and it is more important and impactful to get that number rather than a home number or have confusion over the phone number collected.

**Describe the solution you'd like**
Ask mobile and require as part of the Ask Phone question, triggering the Mobile field to be asked only and the Mobile Opt In to be present on the standard questions rather than construct some questions within the Additional Question feature.

**Describe alternatives you've considered**
Using the Additional Question object or simply relying on the as is functionality where we ask home and mobile question and let the user pick.

**Are you willing and interested in being engaged during the development and testing process?** Yes!

### LINKED ISSUE #469: Receiving Error when registering with the Admin Open Registration link
Receiving Error when registering with the Admin Open Registration link

**To Reproduce**
1. Go to Instance and open the Admin Open Registration link
2. Complete the registration and when hitting submit
3. The Event Closed Display Text appears even though the date is open and capacity remains.

**Expected behavior**
The registration is completed within the form and the registration record is status is Registered.  Currently the registration record is created but is in a Started Status.

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
Thad believes there could be an issue with the URL and how appex is understanding 1.  If we change the URL from "https://uofstthomasmn--edastaging.sandbox.my.salesforce-sites.com/summit__summiteventsconfirmation?adminopen=1&instanceID=a0z8A000001vfh4" to "https://uofstthomasmn--edastaging.sandbox.my.salesforce-sites.com/summit__summiteventsconfirmation?adminopen=TRUE&instanceID=a0z8A000001vfh4" it processes the registration to Registered and displays Confirmation page.

### LINKED ISSUE #472: [FEATURE] Custom Question display style
**Describe the solution you'd like**
On the custom question page registrants would have a more pleasant viewing experience if questions could be full width on the page. Create a display style picklist on the Question object with the values of full width, half width and third width to control the way the question presents on the page.

### LINKED ISSUE #473: [FEATURE] Add Google Analytics campaign tracking codes to registration
**Describe the solution you'd like**

To track the campaign analytic success of a registration google analytic parameters should be recorded on the registration. These should be gathered from the URL, sanitized, and recorded on the registration. Here is a list of those parameters:

- utm_source
- utm_medium
- utm_campaign
- utm_content
- utm_term
- gclid
(Google Click Identifier: Can be uploaded back to the Google Ads platform where they use AI to find similar people)
- utm_id
- utm_source_platform
- utm_creative_format
- utm_marketing_tactic
 
[The definition for each of these parameters can be found here](https://support.google.com/analytics/answer/10917952?hl=en#zippy=%2Cin-this-article).

### LINKED ISSUE #474: Add BCC Transactional Email feature into Summit Events
**Describe the solution you'd like**
As the St. Thomas Visits and Events Team move off of UST Events, they are raising issues on functionality not found in Summit Events.  With this issue, they would like the ability to BCC parents and others when sending out reminders/appointments for perspecitive students.  Within UST Events on a Registration record there is a field to add multiple email addresses, comma sepearated on a record and thus also emailed when sending transactional email. 

Thad mentioned that he has access to the code.

**Are you willing and interested in being engaged during the development and testing process?**
Yes

### LINKED ISSUE #476: [FEATURE] Google data layer script
**Describe the solution you'd like**
Add a simple data layer for Google Tag Manager to each page. 

```
<script>
dataLayer = [{
     'account': ***account_name_if_exists***,
     'recordType': ***recordType_developerName***,
     'eventLabel': ***title_of_event***
}];
</script>
```
*** = to be replaced with data from the event

### LINKED ISSUE #479: [BUG] Auto confirm appointments do not work when appointment page is not visited
**Describe the bug**

If all appointments are auto confirmed and added and required the appointment page is skipped. In scenario the appointment is correctly added without the registrant knowing, but auto confirm is not working by setting the appointment to confirm. This is because the appointment is actually added on the registration page rather than the appointment page. The logic is missing in the first registration page to set confirmed on auto confirmed appointments.

### LINKED ISSUE #480: [BUG] Community logged in user can't progress because of locked fields
**Describe the bug**
If you are logged into a community in salesforce SEA will gather your contact information and fill in the appropriate information on your SEA registration record. This is great but if there is missing information the field will become locked and if that field is required it validation will not allow the registrant to proceed because the locked field is empty.

Solutions:
- Be less zealous about locking fields and restrict it to first, last, email
- Don't lock fields if there is no values for them
- Update validation to ignore locked fields

### LINKED ISSUE #482: [FEATURE] Add data lines for event and instance title
In the Summit Events App REST API feed make event title and instance title two separate data items for easier use of one or the other.

```
[
  {
    title: "Test Event - Secondary Title",
    event_title: "Test Event",
    instance_title: "Secondary Title",
    timezone: "Central Daylight Time (America/Chicago)",
    start: "2023-04-21T08:00:00.000Z",
    sponsors: "",
    longDesc: "",
    locationType: "",
    locationTitle: "The best place in the World",
    locationMapLink: "https://g.page/sociablecider?share",
    locationBuilding: "",
    locationAddress: "123 Evergreen Blvd., St. Paul, MN",
    instanceDesc: "A short description",
    ID: "a06DS000006oMlRYAU",
    feedButtonText: "Register",
    excludeSearchTag: false,
    eventUrl: "https://customization-drive-6989-dev-ed.scratch.my.salesforce-sites.com/SummitEventsRegister?instanceID=a06DS000006oMlRYAU",
    eventClosed: false,
    end: "2023-04-21T15:30:00.000Z",
    description: "This description appears in feed and should be concise",
    className: "eventOpened",
    capacityTotal: 100,
    capacityRemaining: 100
  }
]
```

### LINKED ISSUE #484: [BUG] Close Event Days Before not closing correctly
**Describe the bug**
When Close Event Days Before is set to 4 days it closes earlier than 4 days. Something doesn't add up. Also Keep Registration Open During Event is not closing correctly.

**To Reproduce**

1. Create an event
2. Set the events Additional Configuration "Close Event Days Before" to 4
3. Create an instance that is 5 days before today
4. Event registration should be open but is not

### PR DESCRIPTION
**Pull request by tcdahlberg**
# Critical Changes

# Changes
- Added two data fields to event data returned by REST API: title_event__c, title_instance__c. This splits out the combine title in title to be used easily separated.
-  When a user is logged in to a community and a contact record is found the registration is pre-filled with the contact information. This information was locked to the user then. If the field was empty the user could not progress because the field was locked and validation would not allow any fields to be empty. This bug is fixed.
- When a user is logged in to a community the contact record is automatically connected to the registration. previously this was not happening.
- Appointments that are not shown, but set to auto confirm, will now auto confirm if the appointment page is skipped. Auto building and time are also corrected in this scenario.
- A data layer for google tag manager has been added to pages with account name, audience, event label, category, and sponsor.
- BCC email and status setting are now active on registration.
- utm tracking codes are recorded on registration.
- Custom questions now have a display option to show the question full width, half width and third width. On mobile all fields are full width. This defaults to half width.
- Admin open registration link bug fixed.
- Ask phone now has Ask mobile and Ask mobile and require. Mobile is stripped off the front of the label for this option and text message questions appear.
- Appointment Types with only one item in them for a picklist now appear without erroring.
- Appointment Category and Type can be set on an Appointment Type record and these will be added to the appointment record without asking the registrant for a selection.
- Appointment Type is now recorded on the appointment when set.
- Label fields have been added for the submit page for titles above appointment lists and guest lists.
- When transactional emails are used and fail they fail gracefully now so that registration is not interrupted. This failure is recorded on the activity record. Emails can fail if you reach your org daily limit of 5000 emails (or 15 in scratch orgs).
- Calculations for event closure utilize the Instance Close Date and Time for event closure better. Also system time is set to the time zone of the instance for event relative time comparison. 

# Issues Closed
- Closes #482 
- Closes #480
- Closes #479 
- Closes #476 
- Closes #474 
- Closes #473 
- Closes #472 
- Closes #469 
- Closes #468 
- Closes #467 
- Closes #464 
- Closes #395
- Closes #484

### CODE REVIEW

**Comment by rdblake21** [comment]
Ryan Testing Notes/Comments

# Passed:
✔ #482 
image

✔ #468 & #395 
image
image

✔#479 please review "Needs some Attention"
This passes if you build as expected, but there is room for error.
image

✔ #469 Was able to complete registration with Admin Link on old registration.
image

✔ #467 Worked as anticipated
image

---
---
---
# Needs some attention:
 @tcdahlberg 
 
⛔ #479 Ran into errors due to lack of validation on the setup. There is opportunity for error if the "Chosen State" is Added and Required, but Auto Confirm is not checked. Is there a scenario where something would be "Added and Required" and not auto-confirmed?

Current path when something is not Auto Confirmed, but Added and Required, we get to the Submit/Review Page. If all are auto confirmed, this page is bypassed. When trying to complete registration, there is an error and it just spins. Debug doesn't show anything, but it also doesn't show that it gets to the confirmation page to complete the Registration process. Almost as if it's stuck in a loop...
image
image
image
image

Suggesting that we add some validation, but may need to happen in this package based on timeline.

---
---
---
Need to test still
#480
#476
#474 
#473 
#472 
#467
#464
#484

**Comment by rdblake21** [comment]
# Passed
✔ #479 
Updated fixed the anticipated experience. There are some scenarios that don't make sense that may cause error, like having user input on something that is added and required.  User Input should not have something as added.  Seeing if a Validation Rule can support the control of this.

✔ #484 
This works as expected as the registration link is really what matters.  The formula for Open Registration isn't looking at time so may set some wrong expectations. The formula of Open Registration seems to add complications since it's currently set to look at Date only, not Time. Something worth noting and we may want to add help text.

✔ #464
image
image
image


✔ #474 
No issues, worked as expected

✔ #480 
Setup a community and it works as described. Will want to make sure we articulate that additional configuration is needed is Metadata Types to have that registration update the Contact record.

# Need Review 
@tcdahlberg 

⛔ #472  
Full Width and Half Width have the same outcome.  Third Width works great!
image


# Still need to test
#476
#473

**Comment by rdblake21** [comment]
✔ #472 
With the update, things are working as expected

✔ #476 
Reviewed and the script is on each page within Summit Events. Only page that doesn't have the script is the Cancellation page at this point.

⛔ #473
Tested to see if I could get the utm parameters into the registration record. leveraged the URL builders - https://ga-dev-tools.google/ga4/campaign-url-builder/ - and wasn't able to get the UTMs into their appropriate fields.  Guest User seems to have access to the fields, so not sure what's happening. already pinged Thad about it.
image

**Comment by rdblake21** [comment]
✔ #473 
With the updates, tested and its working as I expect it to
image

**Comment by MaryPatt1** [comment]
#464 
Looks like on the Submit page is pulling in information we don't want. We would just like the [Title] and the [Appointment Type] 

I wasn't sure if my screen shot would load so I also copied and pasted below. Not sure if this is a coding thing or a web thing :)

Faculty Appointment [Title]
Psychology [Appointment Type]
Meet with faculty from the area you choose. [Description]
Psychology  [Appointment Type]

Attend a Class {Appointment Category]
English [Appointment Type]
Attend a class while you are on campus. Please select from the list of majors below! [Description]
English [Appointment Type]
image

**Comment by rdblake21** [comment]
@MaryPatt1 Does this look more like that you're asking for?
Demo Appointment 0 [Title]
Demo Appontment 1 - Ice Cream with Counselor [Title]
English [Appointment Type and Registrant input answer]
Demo Appontment 2 - Meaning of Life [Title]
Registrant Input Answer [Registrant Input Answer]
Demo Appontment 3 - Free Lunch [Title]
Registrant Input Answer [Appointment Type]


Demo Appointment  0 doesn't have input or an Appointment Type
Demo Appointment 1 has an Appointment Type, but the Registrant select it from a drop down menu
Demo Appointment 2 has no Appointment Type, but an answer what requested and input
Demo Appointment 3 doesn't have any input, but has a single Appointment Type associated to the selection

image

**Comment by MaryPatt1** [comment]
Yes, that looks like what we want. Thank you

**Review by rdblake21 — APPROVED** [review]
Tested and Review all changes and updates in this PR.  All comments and issues were tracked in the conversation.  Things are working well in the scratch org, ready to commit to main branch for additional testing and packaging.

**Pull request merged**
