### PR TITLE
Matching validation rule error

### PR DESCRIPTION
**Pull request by tcdahlberg**
# Critical Changes

# Changes
- Registration trigger gets full coverage and doesn't fail even if duplicate rule is not present.
- Matching rule deploys in inactive state

# Issues Closed

### CODE REVIEW

**Comment by rdblake21** [comment]
@jimhubert and @Scarrien, @tcdahlberg did some work on making this not error and it seems to be working.  There was some other refinement and is worth review, testing and asking questions on from your part since you wrote the original.

I'm doing the same thing, so please add comments here.

**Comment by rdblake21** [comment]
I tested and things appear to work as expected, with the right setup.  Tests run on install and pass.  Current package errors if matching rule doesn't exist yet.

@jimhubert and @Scarrien have you had a chance to test this so we can submit for review?

**Comment by tcdahlberg** [comment]
@walt0019, did testing on Summit Event App's duplicate/matching rules mimicking production environments currently functioning. His testing was successful. @rdblake21, I think you can approve this pull request.

**Review by rdblake21 — APPROVED** [review]
We have 3 individuals who've tested successfully and approved all updates.  Merging request based on successful testing from @rdblake21 @tcdahlberg and @walt0019.

This will also fix the error on install,

**Pull request merged**
