### PR TITLE
Feed updates

### PR DESCRIPTION
**Pull request by tcdahlberg**
# Critical Changes

# Changes
- Updated FullCallendar.io javascript package to v6.0.1
- Updated moment.js javascript package to v2.29.4
- Fixed data loading in cumulusci to follow new dev.dataset.sql naming conventions in dev folder
- Removed deploy event records task from culumlus.yml because that is automated with new naming conventions
- Added Filter_Where_To_Display__c and Filter_Category__c for additional feed filtering options (added to layout)
- Added new feature to calendar page that allows for and comma separated list of audience to define what audiences will be shown on the page (example ?audienceList=General%20Public,Current%20Students). This should make this page useful for more general use.
- Added new feedType called parameterKey. When used in a feed url it will display all available parameters that can be sent to a feed with a short description.

# Issues Closed

### CODE REVIEW

**Comment by tcdahlberg** [comment]
Still needs some testing. Especially on the new feed fields.

**Comment by rdblake21** [comment]
@tcdahlberg I'll take a look at this tomorrow and do some thorough testing.  

Are you able to share some ways to test quickly? I don't need a play by play, but just some high level thoughts.

**Comment by rdblake21** [comment]
Initial review, things are looking great!  Still needed to work on the filter parameters and new fields impact as well as placing the calendar elsewhere to full test it out.

**Comment by tcdahlberg** [comment]
Just pushed up a fix because I noticed "Event closed" was appearing on all the events. The easiest way to test this would to create a bunch of events and give them the attributes to filter on.

I would start by checking out the parameter key. To do this, copy the Event Instance Feed URL from any event. My scratch org looks like this:

https://innovation-customization-44-dev-ed.scratch.my.salesforce-sites.com/services/apexrest/summiteventsfeed?eventId=a0B8G000000uGoA&feedType=eventList&viewStart=2022-11-26+00:00:00&viewEnd=2023-1-26+24:59:59

Remove everything from the URL after the question mark like this:

https://innovation-customization-44-dev-ed.scratch.my.salesforce-sites.com/services/apexrest/summiteventsfeed?

And add the feedType=parameterKey to the end of the feel URL like this:

https://innovation-customization-44-dev-ed.scratch.my.salesforce-sites.com/services/apexrest/summiteventsfeed?feedType=parameterKey

That will give you a nice list of the various URL parameters you can pass into the API. You can use parameters in combination, but only if the feedType is set eventList, The values in the parameter key are those found on the fields that control them, so, for instance, if you add a value to audience the parameterKey should reflect it. Also, when using URL parameters they always start with the base URL to the feed, then a question mark (?) and every url parameter after that is delineated by a ampersand (&).

**Comment by rdblake21** [comment]
## Potential Updates (@tcdahlberg)
* Changing the descriptions or creating clarity on the "filter+location" and "filter+building".  I tried this and was confused on how to filter on it - was able to with just using the word building (lowercase) and the parameter description is uppercase which didn't work - **/summiteventsfeed?feedType=eventList&building=Office%20of%20Financial%20Aid**
* Add program filter explanation or details. I see there are six fields, but not sure how it's intended to work quite yet.  If not ready, please call that out.


### Additional Notes/Steps Taken to test:
* Able to filter on various Parameter Keys, including "displayon" and "category", which are new fields.
* Able to Add a new value to a parameter and allow the "Parameter Key" values to change/update.
* Note: per Thad's comment to see the JSON and create your URL string, it's need to be the following
 > https://instanceurl.my.salesforce-sites.com/services/apexrest/summiteventsfeed?feedType=eventlist + **&** + **parameter value from /summiteventsfeed?feedType=parameterKey** + **additional parameters other than Feed Type**.
* > Example: https://aquarius-pumpkinspice-32-dev-ed.scratch.my.salesforce-sites.com/services/apexrest/summiteventsfeed?feedType=eventlist&audience=Party%20People&displayon=All%20Websites
* > Instance URL = https://aquarius-pumpkinspice-32-dev-ed.scratch.
* >Site URL = my.salesforce-sites.com/
* > Feed Reference = services/apexrest/summiteventsfeed?feedType=eventlist
* >Parameter Filters (2 in this case) = &audience=Party%20People&displayon=All%20Websites
* **NOTE: THIS IS ALL CASE SENSATIVE**
* Comma separated list of audience works great!
* ParameterKey Feed Type is awesome, particularly with the descriptions 


### Needs explanation/Support on:
* Getting the Calendar to a Website or external SF Page (demo example - https://github.com/SFDO-Community-Sprints/summit-events-app-documentation/blob/main/docs/Recipes/full-calendar-demo.md) - Can this be leveraged as a recipe for some to "copy, paste and replace" with their instance URL?
* Leverage the feed for custom web development (in documentation, high level, suggestion to work with web developer)


### Need to Test:
* Update CumulucCI and cerate new scratch org to test for loading data

Going to do some more testing shortly!

**Comment by tcdahlberg** [comment]
I just pushed a changed that  removed the location+feed and the changed building+feed to just building. I added a little better description for filter, but probably still doesn't make sense. 

The calendar and using the feed should probably be added as a task to documentation (it's probably already there, I haven't looked) as it's not really packaged code. I will try to work up some really simple uses of the feed to create a list there.

**Comment by rdblake21** [comment]
Completed my testing and have a couple notes:

* push an update to clarify the parameter the &building parameter
* Almost all parameters are working for me
* I can't get the &filter to work anyway I try. I get an XML error when i use "&filter" and everything shows when I tried the various fields.  @tcdahlberg I'm not sure how to test the "filter" in the SummitEventsFeed.cls line 560.  Let me know how to test it and I'll run it again. 
* Spun up another scratch org with an updated cumulusci and it's working as expected.
* Calendar is working as expected, especially compared to the current install link.  should be good there.

@tcdahlberg Let me know about that one filter and after that, I'm feeling good about everything you have here.

**Comment by tcdahlberg** [comment]
I improved unit testing for better feed analysis

**Comment by rdblake21** [comment]
Updated the Anchor Date on the QA .yml file and completed testing.  All is working as expected!

**Review by rdblake21 — APPROVED** [review]
Reviewed and tested the feed updates.  The pull request captures the issues, which have been resolved.  The additional tests help support the errors/issues found and all works as expected now.

**Pull request merged**
