### PR TITLE
isEventClosed method updated

### LINKED ISSUE #576: When an Event marked as cancelled, the closed event text should appear when someone goes to registration page
When an event is marked as Closed or Cancelled, the registration page for the event instances should show the "Event Closed Display Text".  Currently only if the event instance is marked as Closed or Cancelled does it display "Event Closed Display Text".  Some additional comments from Thad below....

Looks like the feed (or REST API) does hide events that are not active. So that is the only place those really do anything. Even there they only look for events that are also active (and ignore every other status)

### PR DESCRIPTION
**Pull request by DavidCuentasMar**
# Critical Changes
- isEventClosed now takes a new argument (master event status)

# Changes
- isEventClosed now checks master event status too

# Issues Closed
Closes #576

### CODE REVIEW

**Comment by rdblake21** [comment]
# Review Guideline (Ryan)
> Walk through of testing process, issues reviewed and identifying any other potential bugs as part of a package or general Pull Request.
---
## Issues to Review
- #576 
---
### Testing Path 
Key:
* ✅ = completed without issue or as expected)
* 🟡 = Met expectations, but potential issues
* ⛔ = Failed testing or met with issues causing missed expectations. Explanation provided)

Testing from Pull Request in VS Code with Scratch Org - 8/30
✅ New Scratch Org WITH Summit Events Installed and Data Loaded via scripts

Paths Tested
* ✅ Sample - Higher Ed/K12 Admissions Tours - Event = Active, Past Date Instance, Closed page test shows
* ✅ Sample - Higher Ed/K12 Admissions Tours - Event = Active, Future Date Instance, Registerable
* ✅ Sample - Higher Ed/K12 Admissions Tours - Event = Active, Future Date Instance = Cancelled, Closed page test shows
* ✅ Sample - Higher Ed/K12 Admissions Tours - Event = Cancelled, Future Date Instance = Active , Closed page test shows

Things are still functioning the way I'd expect!

Items worth noting with this resolve:
* Documentation will need to reflect the value in this as well as what will and won't happen
* Event Closed text should be recommended EARLY in the setup process to ensure that if multiple instance are being created and opened simultaneously, they all have reflected text
* Instance Status will not update, which could impact reporting.  If the Event is closed, but all instances are Active, it may inappropriately reflect any analytics being measured.  Something just to be aware of.

Thanks for handling this @DavidCuentasMar 

@tcdahlberg I'll let you take a look at the code to make sure it aligns with the common style of the app, but all things are functioning the way I'd expect!

**Review by rdblake21 — APPROVED** [review]
Made Comments on the PR, All looks good to me.  Waiting on Thad for code review.

**Comment by rdblake21** [comment]
@tcdahlberg This needs your review with the latest merge.  I think it's a simple fix, but you were going to review anyway.

**Review by tcdahlberg — APPROVED** [review]
Code looks good! Thank you for the contribution.

**Pull request merged**
